import type { Metadata } from 'next'
import { Inter, Noto_Sans } from 'next/font/google'
import './globals.css'

import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import {Header} from "@/components/PageSections/Header/Header";
import {Footer} from "@/components/PageSections/Footer/Footer";
config.autoAddCss = false

const notoSans = Noto_Sans({
  subsets: ['latin'],
  weight: '700',
  variable: '--font-noto-sans',
})

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={notoSans.className + ` flex flex-col min-h-screen`}>
        <Header/>
          <div className="flex-grow">
            {children}
          </div>
        <Footer/>
      </body>
    </html>
  )
}
